/**
 * iris
 * Generated by GAIA Scaffolder
 */

import { chromium, Browser, BrowserContext, Page } from 'playwright';
import { GaiaAgent } from '../../../pkg/core';
import manifest from '../manifest.json';

class Iris extends GaiaAgent {
  private browser: Browser | null = null;
  private context: BrowserContext | null = null;
  private page: Page | null = null;

  constructor() {
    super({
      manifest: manifest as any,
      kernelURL: process.env.GAIA_KERNEL_URL || 'http://localhost:8080'
    });

    // Register Browser Capabilities
    this.registerCapability('navigate', this.handleNavigate.bind(this));
    this.registerCapability('click', this.handleClick.bind(this));
    this.registerCapability('type', this.handleType.bind(this));
    this.registerCapability('scrape', this.handleScrape.bind(this));
  }

  /**
   * lazyInit ensures the browser is launched only when needed.
   */
  private async lazyInit() {
    if (!this.browser) {
      console.log(`[${this.manifest.agent_id}] Launching headless browser...`);
      this.browser = await chromium.launch({ headless: true });
      this.context = await this.browser.newContext({
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
      });
      this.page = await this.context.newPage();
    }
  }

  private async handleNavigate(input: { url: string; wait_until?: any }) {
    await this.lazyInit();
    console.log(`[${this.manifest.agent_id}] Navigating to: ${input.url}`);
    
    await this.page!.goto(input.url, { 
      waitUntil: input.wait_until || 'domcontentloaded',
      timeout: 30000 
    });

    return { 
      status: 'success', 
      url: this.page!.url(),
      title: await this.page!.title() 
    };
  }

  private async handleClick(input: { selector: string; timeout?: number }) {
    await this.lazyInit();
    console.log(`[${this.manifest.agent_id}] Clicking: ${input.selector}`);
    
    await this.page!.click(input.selector, { 
      timeout: input.timeout || 10000 
    });

    return { status: 'success', selector: input.selector };
  }

  private async handleType(input: { selector: string; text: string; delay?: number }) {
    await this.lazyInit();
    console.log(`[${this.manifest.agent_id}] Typing into: ${input.selector}`);
    
    await this.page!.fill(input.selector, input.text, { 
      timeout: 10000 
    });

    return { status: 'success', selector: input.selector };
  }

  private async handleScrape(input: { selector: string; multiple?: boolean }) {
    await this.lazyInit();
    console.log(`[${this.manifest.agent_id}] Scraping: ${input.selector}`);
    
    let results: string[] = [];
    if (input.multiple) {
      results = await this.page!.$$eval(input.selector, el => el.map(e => e.textContent || ''));
    } else {
      const text = await this.page!.textContent(input.selector);
      if (text) results.push(text.trim());
    }

    return { results };
  }

  // Override stop to cleanup browser
  public async stop(): Promise<void> {
    if (this.browser) {
      await this.browser.close();
    }
    await super.stop();
  }
}

const agent = new Iris();
agent.start().catch(err => {
  console.error('Failed to start agent:', err);
  process.exit(1);
});
