/**
 * GAIA Agent Scaffolder
 * Usage: npm run create-agent -- my-new-agent
 */

import * as fs from 'fs';
import * as path from 'path';

const agentName = process.argv[2];

if (!agentName) {
  console.error('Error: Please provide an agent name.');
  console.error('Usage: npm run create-agent -- <agent-name>');
  process.exit(1);
}

const targetDir = path.join(__dirname, '../agents', agentName);

if (fs.existsSync(targetDir)) {
  console.error(`Error: Agent directory '${agentName}' already exists.`);
  process.exit(1);
}

console.log(`🏗  Scaffolding new GAIA Agent: ${agentName}...`);

// 1. Create directory structure
fs.mkdirSync(path.join(targetDir, 'src'), { recursive: true });

// 2. Generate manifest.json
const manifest = {
  agent_id: agentName,
  version: "1.0.0",
  endpoint: "http://localhost:3000",
  transport: "http",
  protocol: "native",
  state_requirements: {
    required: true,
    max_bytes: 10240
  },
  capabilities: [
    {
      name: "hello_world",
      description: "A sample capability for the new agent",
      input_schema: {
        type: "object",
        properties: {
          name: { type: "string" }
        }
      },
      output_schema: {
        type: "object",
        properties: {
          greeting: { type: "string" }
        }
      }
    }
  ]
};

// 3. Generate package.json
const pkg = {
  name: `@gaia-agents/${agentName}`,
  version: "1.0.0",
  private: true,
  scripts: {
    "start": "ts-node src/index.ts",
    "dev": "ts-node src/index.ts"
  },
  dependencies: {
    "@gaia-agents/core": "file:../../pkg/core"
  }
};

// 4. Generate src/index.ts
const indexTs = `/**
 * ${agentName}
 * Generated by GAIA Scaffolder
 */

import { GaiaAgent } from '../../pkg/core';
import manifest from '../manifest.json';

class ${agentName.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('')} extends GaiaAgent {
  constructor() {
    super({
      manifest: manifest as any,
      kernelURL: process.env.GAIA_KERNEL_URL || 'http://localhost:8080'
    });

    // Register your capability handlers here
    this.registerCapability('hello_world', this.handleHello.bind(this));
  }

  private async handleHello(input: { name: string }) {
    console.log(\`[\${manifest.agent_id}] Received hello request for: \${input.name}\`);

    // Use Tier 4 Managed State
    const count = await this.state.get<number>('visit_count') || 0;
    await this.state.set('visit_count', count + 1);

    return { 
      greeting: \`Hello \${input.name}! This agent has been called \${count + 1} times.\` 
    };
  }
}

const agent = new ${agentName.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('')}();
agent.start().catch(err => {
  console.error('Failed to start agent:', err);
  process.exit(1);
});
`;

// Write files
fs.writeFileSync(path.join(targetDir, 'manifest.json'), JSON.stringify(manifest, null, 2));
fs.writeFileSync(path.join(targetDir, 'package.json'), JSON.stringify(pkg, null, 2));
fs.writeFileSync(path.join(targetDir, 'src/index.ts'), indexTs);

console.log(`✅  Success! Created ${agentName} in agents/${agentName}`);
console.log(`\nTo get started:`);
console.log(`  cd agents/${agentName}`);
console.log(`  npm install`);
console.log(`  npm start`);
`;
